-- Create CONG_VIEC table
CREATE TABLE CONG_VIEC (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    TenCongViec NVARCHAR2(200) NOT NULL,
    MoTa NVARCHAR2(2000),
    TrangThai NVARCHAR2(50) DEFAULT 'Mới' NOT NULL,
    DoUuTien NVARCHAR2(50) DEFAULT 'TrungBinh' NOT NULL,
    NguoiPhuTrachId NUMBER,
    NgayBatDau TIMESTAMP NOT NULL,
    NgayKetThuc TIMESTAMP,
    NgayTao TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    NgayCapNhat TIMESTAMP,
    CONSTRAINT FK_CongViec_User FOREIGN KEY (NguoiPhuTrachId) REFERENCES USERS(Id)
);

-- Create indexes
CREATE INDEX IDX_CongViec_TrangThai ON CONG_VIEC(TrangThai);
CREATE INDEX IDX_CongViec_DoUuTien ON CONG_VIEC(DoUuTien);
CREATE INDEX IDX_CongViec_NguoiPhuTrach ON CONG_VIEC(NguoiPhuTrachId);
CREATE INDEX IDX_CongViec_NgayBatDau ON CONG_VIEC(NgayBatDau);

COMMIT;
