-- Create Users Table
CREATE TABLE USERS (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Username VARCHAR2(100) NOT NULL UNIQUE,
    Email VARCHAR2(255) NOT NULL UNIQUE,
    PasswordHash VARCHAR2(500) NOT NULL,
    IsActive NUMBER(1) DEFAULT 1 NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE INDEX idx_users_username ON USERS(Username);
CREATE INDEX idx_users_email ON USERS(Email);
