-- Create Roles Table
CREATE TABLE ROLES (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL UNIQUE,
    Description VARCHAR2(500)
);

-- Create Permissions Table
CREATE TABLE PERMISSIONS (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL UNIQUE,
    ResourceName VARCHAR2(100) NOT NULL,
    Action VARCHAR2(50) NOT NULL
);

-- Create User_Roles Junction Table
CREATE TABLE USER_ROLES (
    UserId NUMBER NOT NULL,
    RoleId NUMBER NOT NULL,
    PRIMARY KEY (UserId, RoleId),
    FOREIGN KEY (UserId) REFERENCES USERS(Id) ON DELETE CASCADE,
    FOREIGN KEY (RoleId) REFERENCES ROLES(Id) ON DELETE CASCADE
);

-- Create Role_Permissions Junction Table
CREATE TABLE ROLE_PERMISSIONS (
    RoleId NUMBER NOT NULL,
    PermissionId NUMBER NOT NULL,
    PRIMARY KEY (RoleId, PermissionId),
    FOREIGN KEY (RoleId) REFERENCES ROLES(Id) ON DELETE CASCADE,
    FOREIGN KEY (PermissionId) REFERENCES PERMISSIONS(Id) ON DELETE CASCADE
);

CREATE INDEX idx_user_roles_userid ON USER_ROLES(UserId);
CREATE INDEX idx_role_permissions_roleid ON ROLE_PERMISSIONS(RoleId);
