-- Create Modules Table
CREATE TABLE MODULES (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL UNIQUE,
    Version VARCHAR2(50) NOT NULL,
    IsEnabled NUMBER(1) DEFAULT 1 NOT NULL,
    LoadOrder NUMBER DEFAULT 0 NOT NULL
);

CREATE INDEX idx_modules_name ON MODULES(Name);
CREATE INDEX idx_modules_enabled ON MODULES(IsEnabled);
