-- Create Products Table
CREATE TABLE PRODUCTS (
    Id NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(200) NOT NULL,
    Description VARCHAR2(1000),
    Price NUMBER(10, 2) NOT NULL,
    StockQuantity NUMBER DEFAULT 0 NOT NULL,
    IsActive NUMBER(1) DEFAULT 1 NOT NULL,
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UpdatedAt TIMESTAMP
);

CREATE INDEX idx_products_name ON PRODUCTS(Name);
CREATE INDEX idx_products_active ON PRODUCTS(IsActive);
